language: node_js
node_js:
  - "node"
  - "lts/*"
before_script:
  - npm install -g grunt
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: grunt test
    - stage: "Build"
      name: "build"
      script: grunt
    - stage: "Release"
      node_js: "lts/*"
      deploy:
        provider: releases
        api_key: $NPM_API_KEY
        script: npm publish --tag ${TRAVIS_TAG}
        on:
          tags: true
