language: node_js
node_js:
  - "node"
  - "lts/*"
before_script:
  - npm install -g grunt
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: grunt test
    - stage: "Build"
      name: "build"
      script: grunt
